Bump Istio to 1.23.2
kyma-project/istio pull request #1024
Opened 2024-09-24 06:06 UTC by werdes72

**Description**

Changes proposed in this pull request:

- Update Istio version to 1.23.2

**Pre-Merge Checklist**

- [ ] As a PR reviewer, verify code coverage and evaluate if it is acceptable.

**Related issues**
- https://github.com/kyma-project/istio/issues/998

2024-09-24 11:16 UTC, kolodziejczak requested changes
Please update also compatibility mode documentation with the envs change

2024-09-24 11:16 UTC, kolodziejczak commented on api/v1alpha2/compatibility_mode_test.go
> +			deltaXds := getProxyMetadataField(out, "ENABLE_DELIMITED_STATS_TAG_REGEX")
Variable name should also be changed here

2024-09-24 11:16 UTC, kolodziejczak commented on api/v1alpha2/compatibility_mode_test.go
> +			xdsAgent := getProxyMetadataField(out, "ENABLE_DEFERRED_CLUSTER_CREATION")
Variable name should also be changed here

2024-09-24 11:16 UTC, kolodziejczak commented on go.mod
> +	istio.io/istio v0.0.0-20240917190016-da0b3f29e9f9
I think it should be 1.23.2 here

2024-09-24 11:16 UTC, kolodziejczak commented on internal/istiooperator/istio-operator-light.yaml
Can you point me to the documentation/source for changes here?

2024-09-24 11:16 UTC, kolodziejczak commented on api/v1alpha2/compatibility_mode_test.go
I think there are more tests that should be adjusted.

2024-09-24 11:22 UTC, werdes72 commented on internal/istiooperator/istio-operator-light.yaml
It's in the PR description: https://github.com/istio/istio/blob/1d4f23f70b4d6bf0a71995808393b7523199cc7c/releasenotes/notes/51987.yaml#L8

2024-09-24 11:56 UTC, kolodziejczak commented on internal/istiooperator/istio-operator-light.yaml
thanks!

2024-09-25 12:24 UTC, kolodziejczak approved these changes

2024-09-25 12:28 UTC, nataliasitko approved these changes

2024-09-25 12:33 UTC, merged