Bump Istio to 1.24
kyma-project/istio pull request #1149
Opened 2024-11-26 10:18 UTC by barchw

**Description**

Changes proposed in this pull request:

- Bump Istio to 1.24

**Pre-Merge Checklist**

- [ ] As a PR reviewer, verify code coverage and evaluate if it is acceptable.

**Related issues**

2024-11-28 14:08 UTC, triffer requested changes

2024-11-29 06:08 UTC, triffer approved these changes

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +This version change involves the following changes to compatibility version parameters:
```suggestion
This version includes the following changes to compatibility version parameters.
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +Previous compatibility version parameters switching from false to true:
```suggestion
The parameters for the previous compatibility version are switched from 'false' to 'true':
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +New compatibility version parameters switching set to false:
```suggestion
This compatibility version applies the new parameters set to `false`:
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +| ENABLE\_ENHANCED\_DESTINATIONRULE\_MERGE              | If enabled, Istio merge DestinationRules considering their exportTo fields, they will be kept as independent rules if the exportTos are not e
```suggestion
| ENABLE\_ENHANCED\_DESTINATIONRULE\_MERGE              | If enabled, Istio merges DestinationRules considering their **exportTo** fields. The DestinationRules are then kept as independent rules if the **exportTo** fields are not equal. |
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +| PILOT\_UNIFIED\_SIDECAR\_SCOPE                        | If true, unified SidecarScope creation will be used. This is only intended as a temporary feature flag for backwards compatibility.
```suggestion
| PILOT\_UNIFIED\_SIDECAR\_SCOPE                        | If true, unified SidecarScope creation is used. This is only intended as a temporary feature flag for backward compatibility.                |
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +| ENABLE\_DEFERRED\_STATS\_CREATION                     | If enabled, Istio will lazily initialize a subset of the stats.
```suggestion
| ENABLE\_DEFERRED\_STATS\_CREATION                     | If enabled, Istio lazily initializes a subset of the stats.                                                                                    |
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +| BYPASS\_OVERLOAD\_MANAGER\_FOR\_STATIC\_LISTENERS     | If enabled, overload manager will not be applied to static listeners.
```suggestion
| BYPASS\_OVERLOAD\_MANAGER\_FOR\_STATIC\_LISTENERS     | If enabled, the overload manager is not applied to static listeners.                                                                              |
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +| EXCLUDE\_UNSAFE\_503\_FROM\_DEFAULT\_RETRY            | If true, excludes unsafe retry on 503 from default retry policy.
```suggestion
| EXCLUDE\_UNSAFE\_503\_FROM\_DEFAULT\_RETRY            | If true, excludes unsafe retry on `503` from the default retry policy.                                                                                   |
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +| PREFER\_DESTINATIONRULE\_TLS\_FOR\_EXTERNAL\_SERVICES | If true, external services will prefer the TLS settings from DestinationRules over the metadata TLS settings.
```suggestion
| PREFER\_DESTINATIONRULE\_TLS\_FOR\_EXTERNAL\_SERVICES | If true, external services prefer the TLS settings from DestinationRules over the metadata TLS settings.                                      |
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +| ENABLE\_INBOUND\_RETRY\_POLICY       | If true, enables retry policy for inbound routes which automatically retries requests that were reset before it reaches the service.
```suggestion
| ENABLE\_INBOUND\_RETRY\_POLICY       | If true, enables retry policy for inbound routes, which automatically retries any requests that were reset before reaching the intended service.                                                |
```

2024-12-02 07:28 UTC, nataliasitko commented on docs/release-notes/1.12.0.md
> +| ENABLE\_DEFERRED\_CLUSTER\_CREATION  | If enabled, Istio will create clusters only when there are requests. This will save memory and CPU cycles in cases where there are lots of inactive clusters a
```suggestion
| ENABLE\_DELIMITED\_STATS\_TAG\_REGEX | If true, pilot uses the new delimited stat tag regex to generate Envoy stats tags.                                                                                              |
| ENABLE\_DEFERRED\_CLUSTER\_CREATION  | If enabled, Istio creates clusters only when there are requests. This saves memory and CPU cycles in cases where there are lots of inactive clusters and more than one worker thread. |
```

2024-12-02 11:55 UTC, nataliasitko approved these changes

2024-12-02 13:24 UTC, nataliasitko approved these changes

2024-12-02 13:25 UTC, merged