Update VERSION
kyma-project/istio pull request #1164
Opened 2024-12-03 13:29 UTC by barchw

**Description**

Changes proposed in this pull request:

- ...

**Pre-Merge Checklist**

- [ ] As a PR reviewer, verify code coverage and evaluate if it is acceptable.

**Related issues**

2024-12-03 13:49 UTC, triffer requested changes

2024-12-03 13:49 UTC, triffer commented on sec-scanners-config.yaml
> +  - europe-docker.pkg.dev/kyma-project/prod/istio/main/istio-manager:1.11.0
```suggestion
  - europe-docker.pkg.dev/kyma-project/prod/istio/releases/istio-manager:1.11.0
```

2024-12-03 13:51 UTC, barchw commented on sec-scanners-config.yaml
> +  - europe-docker.pkg.dev/kyma-project/prod/istio/main/istio-manager:1.11.0
Ah, right

2024-12-03 13:59 UTC, triffer approved these changes

2024-12-04 12:14 UTC, Ressetkk approved these changes

2024-12-04 12:20 UTC, merged