Extend Istio CR with Egress Gateway
kyma-project/istio pull request #1178
Opened 2024-12-09 08:23 UTC by werdes72

**Description**

Changes proposed in this pull request:

- Add Egress Gateway to Istio custom resource API
- Unit tests

**Pre-Merge Checklist**

- [ ] As a PR reviewer, verify code coverage and evaluate if it is acceptable.

**Related issues**
#1159

2024-12-13 07:35 UTC, nataliasitko commented on docs/user/04-00-istio-custom-resource.md
> +| **components.egressGateway.enabled**                        | bool           | Enables Istio Egress Gateway
```suggestion
| **components.egressGateway.enabled**                        | bool           | Enables Istio Egress Gateway.                                                                                                                                                                                                                                                                                                                 |
```

2024-12-13 07:38 UTC, nataliasitko submitted a review, later dismissed

2024-12-16 10:17 UTC, videlov commented on api/v1alpha2/merge_test.go
> +			})
```suggestion
				iopEnabled := out.Spec.Components.EgressGateways[0].Enabled.GetValue()
				Expect(iopEnabled).To(Equal(enabled))
			})
```

2024-12-17 12:29 UTC, nataliasitko approved these changes

2024-12-17 14:04 UTC, videlov requested changes

2024-12-17 14:04 UTC, videlov commented on internal/filter/predicate.go
> +type EgressGatewayPredicate interface {
do we need this, since you removed the restarter ?

2024-12-18 08:11 UTC, videlov approved these changes

2024-12-18 08:27 UTC, nataliasitko approved these changes

2024-12-18 08:42 UTC, merged