Istio version checking
kyma-project/istio pull request #126
Opened 2023-04-12 07:59 UTC by werdes72

See: #124

2023-04-12 09:15 UTC, barchw requested changes

2023-04-12 09:15 UTC, barchw commented on internal/reconciliations/istio/configuration.go
> +}
```suggestion
type helperVersion semver.Version
```

2023-04-12 09:15 UTC, barchw commented on internal/reconciliations/istio/configuration.go
> +	return helperVersion{ver: *version}, err
We should check for nil

2023-04-12 09:15 UTC, barchw commented on internal/reconciliations/istio/configuration.go
> +	return current.ver.Major >= target.ver.Major && current.ver.Minor >= target.ver.Minor && current.ver.Patch > target.ver.Patch
```suggestion
	return target.ver.LessThan(current.ver)
```

2023-04-12 09:15 UTC, barchw commented on internal/reconciliations/istio/configuration.go
> +func amongOneMajor(first, second helperVersion) bool {
```suggestion
func sameMajorVersion(first, second helperVersion) bool {
```

2023-04-12 09:15 UTC, barchw commented on internal/reconciliations/istio/configuration.go
> +		return fmt.Errorf("target Istio version (%s) is higher than current Istio version (%s) - major version upgrade is not supported", targetIstioVersion.ver.String(), currentIstioVersion.ver.String())
```suggestion
		return fmt.Errorf("target Istio version (%s) is different than current Istio version (%s) - major version upgrade is not supported", targetIstioVersion.ver.String(), currentIstioVersion.ver.String())
```

2023-04-12 12:22 UTC, werdes72 commented on internal/reconciliations/istio/configuration.go
> +}
Removed helper type.

2023-04-13 06:18 UTC, barchw approved these changes
/meow

2023-04-13 06:20 UTC, merged