Module migration
kyma-project/istio pull request #176
Opened 2023-06-12 13:44 UTC by triffer

**Description**

Changes proposed in this pull request:

- Add v1alpha2 CRD as storage version
- Rename istio-sample CR to default

**Related issue(s)**
- https://github.com/kyma-project/istio/issues/168

2023-06-12 14:15 UTC, triffer commented
/test pull-istio-module-build

2023-06-12 14:17 UTC, triffer commented
/test pull-istio-module-build

2023-06-14 11:52 UTC, triffer commented
/test pull-istio-integration

2023-06-15 09:41 UTC, videlov requested changes

2023-06-15 13:45 UTC, triffer commented on api/v1alpha2/istio_types.go
> +type IstioSpec struct {
The Istio CRD includes version v1alpha1 from Kyma repo, so we are fine.

2023-06-15 14:39 UTC, videlov commented
/test pull-istio-lint

2023-06-16 06:01 UTC, merged