Warning status
kyma-project/istio pull request #209
Opened 2023-07-07 10:06 UTC by werdes72

**Description**

Changes proposed in this pull request:
- Add warning status to Istio module

**Related issue(s)**
https://github.com/kyma-project/lifecycle-manager/issues/525

2023-07-10 06:42 UTC, barchw requested changes
Unit test coverage is missing

2023-07-10 06:42 UTC, barchw commented on internal/status/status.go
> +func (DefaultStatusHandler) SetWarning(ctx context.Context, err described_errors.DescribedError, client client.Client, istioCR *operatorv1alpha1.Istio, condition metav1.Condition, retryTime ...time.D
As warning is also a `described_error` I think that moving the logic under `SetError` func would make more sense (so we should set `istioCR.Status.State` based on err.level()). Then the new logic in https://github.com/kyma-project/istio/blob/fa38c94d0718c4153f1d2adf55452206d3b0edba/controllers/istio_controller.go#L84 could be removed, only leaving SetError at the end.

2023-07-10 06:42 UTC, barchw commented on internal/reconciliations/proxy/sidecars_test.go
> +
Maybe the name for `described_errors.DescribedError` should be adjusted (e.g. `described_errors.DescribedState`)?

2023-07-11 07:05 UTC, barchw submitted a review, later dismissed

2023-07-11 07:59 UTC, nataliasitko commented on docs/user/01-20-istio-custom-resource.md
> +| **state** (required) | string | Signifies the current state of **CustomObject**. Its value can be either `Ready`, `Processing`, `Error`, `Warning` or `Deleting`. |
```suggestion
| **state** (required) | string | Signifies the current state of **CustomObject**. Its value can be either `Ready`, `Processing`, `Error`, `Warning`, or `Deleting`. |
```

2023-07-11 09:45 UTC, nataliasitko approved these changes

2023-07-11 10:03 UTC, barchw approved these changes

2023-07-11 10:22 UTC, merged