Don't create kyma gateway
kyma-project/istio pull request #449
Opened 2023-10-30 12:42 UTC by werdes72

**Description**

Changes proposed in this pull request:

- Remove code responsible for creating kyma gateway 

**Related issue(s)**
#448

2023-10-31 11:54 UTC, videlov commented
Please check also docs and remove / adapt:
https://github.com/kyma-project/istio/blob/main/docs/contributor/04-10-technical-design.md#istio-resources
https://github.com/kyma-project/istio/blob/main/docs/contributor/04-40-istio-resources.md

2023-10-31 11:55 UTC, videlov requested changes
Please check also docs and remove / adapt:
https://github.com/kyma-project/istio/blob/main/docs/contributor/04-10-technical-design.md#istio-resources
https://github.com/kyma-project/istio/blob/main/docs/contributor/04-40-istio-resources.md

2023-11-02 06:51 UTC, nataliasitko approved these changes

2023-11-02 08:50 UTC, videlov commented
this PR:
```✗ This PR is lowering code coverage compared to main branch! Please add tests.```

but it is removing stuff, we can accept it as an exception.

2023-11-02 08:50 UTC, videlov approved these changes

2023-11-02 08:50 UTC, merged