Bump Istio to 1.20
kyma-project/istio pull request #483
Opened 2023-11-20 13:42 UTC by videlov

**Description**

Changes proposed in this pull request:

- Bump Istio to 1.20
- https://istio.io/latest/news/releases/1.20.x/announcing-1.20/

**Related issue(s)**

https://github.com/kyma-project/istio/issues/477

2023-11-22 13:28 UTC, barchw requested changes

2023-11-22 14:16 UTC, videlov commented on manifests/istio-operator-template.yaml
> +        readinessFailureThreshold: 40
I did try them, but we introduce downtime with these settings. With our zero downtime test I was able to narrow it down to these new defaults. We will discuss it tomorrow after daily.

2023-11-22 15:05 UTC, videlov commented on manifests/istio-operator-template.yaml
> +        readinessFailureThreshold: 40
I did find an alternative in relaxing readiness settings for `istio-proxy`. Issue was with `readinessInitialDelaySeconds: 0` , I did leave it to 5 secs and can not observe downtime on Istio install or rollout restart of the deployment.

2023-11-23 09:54 UTC, videlov commented on manifests/istio-operator-template.yaml
> +        readinessFailureThreshold: 40
We decided to introduced the more relaxed polling period for readiness and keep the previous threshold of around 200 secs.

2023-11-23 10:02 UTC, nataliasitko commented on docs/release-notes/1.2.0.md
> +- Add Client IP in XFF header for AWS [#443](https://github.com/kyma-project/istio/pull/443)
```suggestion
- Add the client IP in the XFF header for AWS [#443](https://github.com/kyma-project/istio/pull/443)
```

2023-11-23 11:53 UTC, barchw approved these changes

2023-11-23 12:07 UTC, nataliasitko approved these changes

2023-11-23 12:09 UTC, merged