Move Prow to GHA
kyma-project/istio pull request #584
Opened 2024-01-25 09:24 UTC by barchw

**Description**

Changes proposed in this pull request:

- ...

**Related issues**

2024-01-29 13:03 UTC, barchw commented
/override pull-istio-operator-integration-gcp

2024-01-29 13:25 UTC, kolodziejczak requested changes
We are missing AWS specific integration test on main and PR to release branches

2024-01-30 07:58 UTC, barchw commented
> We are missing AWS specific integration test on main and PR to release branches

@kolodziejczak I would say we need to re-discuss that topic again
If anything we could still do it in follow up to this one, so that's how I would do it if we agree on running on PRs as well

2024-01-31 08:29 UTC, kolodziejczak requested changes

2024-01-31 08:29 UTC, kolodziejczak commented on hack/ci/gardener-integration-aws-specific.sh
> +make install deploy aws-integration-test
Make target `aws-integration-test` already contains install and deploy embedded

2024-01-31 08:29 UTC, kolodziejczak commented on hack/ci/gardener-integration-aws-specific.sh
> +#!/usr/bin/env bash
We have already a script for that in tests/integration/scripts. I assume this is a way of duplicating scripts so prow won't fail after merging?

2024-01-31 08:29 UTC, kolodziejczak commented on .github/workflows/main-integration.yaml
> +  istio-integration-gcp:
we didn't have this job on post main, but in my opinion more jobs is ok

2024-01-31 08:29 UTC, kolodziejczak commented on .github/workflows/main-integration.yaml
> +      - run: make IMG="europe-docker.pkg.dev/kyma-project/prod/istio-manager:${{github.sha}}" gardener-istio-integration-test
This target also wasn't running on post main, but also in my opinion ok to have it here

2024-01-31 08:29 UTC, kolodziejczak commented on .github/workflows/pull-integration-rel.yaml
> +  istio-integration-aws:
job with this target was running on GCP in prow

2024-01-31 11:03 UTC, kolodziejczak approved these changes

2024-01-31 11:05 UTC, barchw commented
/override pull-istio-operator-integration-gcp

2024-02-02 07:50 UTC, barchw commented
/override pull-istio-operator-integration-gcp

2024-02-02 08:18 UTC, merged