Update istio to 1.21.0
kyma-project/istio pull request #676
Opened 2024-03-18 08:22 UTC by barchw

**Description**

Changes proposed in this pull request:

- Update istio to 1.21.0

**Related issues**
- https://github.com/kyma-project/istio/issues/671

2024-03-29 11:05 UTC, barchw commented on tests/integration/features/istio/evaluation/istio_installation_demo.feature
> +    #Then "proxy" has "requests" set to cpu - "10m" and memory - "32Mi"
Int tests for egress and proxy - follow up

2024-03-29 11:06 UTC, barchw commented on internal/restarter/ingress_gateway.go
> +			ctrl.Log.Info("Retrying ingress gateway restart")
Follow up - logging levels

2024-04-02 07:33 UTC, kolodziejczak requested changes

2024-04-02 07:44 UTC, barchw commented on tests/integration/steps/destination_rule.go
> +	"istio.io/client-go/pkg/apis/networking/v1alpha3"
We should use the same, latest version in all our packages, all the others use v1alpha3

2024-04-02 07:45 UTC, barchw commented on tests/integration/steps/istio.go
> +		//		}
This one yes

2024-04-02 07:46 UTC, barchw commented on tests/integration/features/istio/evaluation/istio_installation_demo.feature
> +    #Then "proxy" has "requests" set to cpu - "10m" and memory - "32Mi"
No, this should stay, as the tests should be implemented in a follow up.
This feature should not change, only the implementation

2024-04-02 14:07 UTC, barchw commented on internal/istiooperator/istio-operator-light.yaml
> +        repairPods: false
The repair pods need to be false, and delete true until https://github.com/istio/istio/commit/678762f4614c86e316612ffa8ac9d0b42acfce35 becomes available in a release. Without it, repair fails

2024-04-03 07:02 UTC, barchw commented
/hold - need to check controlled resources list

2024-04-03 07:53 UTC, barchw commented on internal/resources/controlled_resources_list.yaml
> -  - GroupVersionKind:
Create a follow up card
TODO: Validate that it is not blocking deletion after upgrade from 1.20.3

2024-04-03 08:10 UTC, barchw commented on internal/resources/controlled_resources_list.yaml
> -  - GroupVersionKind:
Verified TODO, looks good

2024-04-03 08:35 UTC, barchw commented
/unhold

2024-04-03 09:55 UTC, nataliasitko commented on docs/release-notes/1.5.0.md
> +- Discontinue support for `Referer` headers containing user info or fragment components. The new sanitization behaviour is described [here](https://www.envoyproxy.io/docs/envoy/v1.26.7/configuration/
```suggestion
- Discontinue support for `Referer` headers containing user info or fragment components. The new sanitization behavior is described in the [Envoy's documentation](https://www.envoyproxy.io/docs/envoy/v1.26.7/configuration/http/http_conn_man/headers#config-http-conn-man-headers-referer).
```

2024-04-03 09:55 UTC, nataliasitko commented on docs/release-notes/1.5.0.md
> +- Istio no longer creates `IstioOperator/installed-state` CustomResource after installation. See the upstream [Istio Issue](https://github.com/istio/istio/issues/44814) and [Pull Request](https://git
```suggestion
- Istio no longer creates `IstioOperator/installed-state` CustomResource after installation. See the upstream [Istio issue](https://github.com/istio/istio/issues/44814) and the [PR](https://github.com/istio/istio/pull/47860) for more information.
```

2024-04-03 09:55 UTC, nataliasitko commented on docs/release-notes/1.5.0.md
> +## Breaking Changes in Istio upstream
```suggestion
## Breaking Changes in Istio Upstream
```

2024-04-03 13:16 UTC, kolodziejczak submitted a review, later dismissed

2024-04-04 06:07 UTC, nataliasitko commented on docs/release-notes/1.5.0.md
> +## Breaking Changes in Istio Upstream
```suggestion
## Relevant Changes in Istio Upstream
```

2024-04-04 06:27 UTC, nataliasitko approved these changes

2024-04-04 07:07 UTC, merged